import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const SUPABASE_URL='https://pmwagzylqgxzigtizaqb.supabase.co';
const SUPABASE_KEY='REPLACE_WITH_ELF_PUBLISHABLE_KEY';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);let user=null;
async function init(){const {data}=await supabase.auth.getSession();user=data.session?.user||null;render();if(user)loadPosts();}
function render(){ $('auth').hidden=!!user;$('app').hidden=!user; }
$('signup').addEventListener('submit',async e=>{e.preventDefault();$('authMsg').textContent='Creating account...';const username=$('username').value.trim();const {data,error}=await supabase.auth.signUp({email:$('email').value,password:$('password').value,options:{data:{username,display_name:username}}});if(error){$('authMsg').textContent=error.message;return}if(data.user){user=data.user;render();loadPosts();}});
$('login').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){$('authMsg').textContent=error.message;return}user=data.user;render();loadPosts();});
$('logout').onclick=async()=>{await supabase.auth.signOut();user=null;render()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const tab=b.dataset.tab;$('feed').hidden=tab!=='feed';$('chat').hidden=tab!=='chat';if(tab==='chat')loadConversations()});
async function loadPosts(){const {data,error}=await supabase.from('posts').select('id,media_url,media_type,caption,created_at,profiles(username)').is('removed_at',null).order('created_at',{ascending:false}).limit(50);if(error)return;const box=$('posts');box.innerHTML=data.map(p=>`<article class="post"><div class="meta">@${escapeHtml(p.profiles?.username||'user')} · ${new Date(p.created_at).toLocaleString()}</div>${p.caption?`<p>${escapeHtml(p.caption)}</p>`:''}${p.media_type==='video'?`<video src="${p.media_url}" controls></video>`:`<img src="${p.media_url}" alt="ELF post">`}<button onclick="reportPost('${p.id}')">Report</button></article>`).join('')||'<p>No posts yet.</p>';}
$('postForm').addEventListener('submit',async e=>{e.preventDefault();const file=$('media').files[0];if(!file||!user)return;const ext=file.name.split('.').pop().toLowerCase();const type=file.type.startsWith('video/')?'video':'image';const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const {error:up}=await supabase.storage.from('elf-media').upload(path,file,{contentType:file.type});if(up){alert(up.message);return}const {data:{publicUrl}}=supabase.storage.from('elf-media').getPublicUrl(path);const {error}=await supabase.from('posts').insert({user_id:user.id,media_url:publicUrl,media_type:type,caption:$('caption').value.trim()});if(error)alert(error.message);else{$('postForm').reset();loadPosts()}});
window.reportPost=async id=>{const reason=prompt('Why are you reporting this post?');if(reason)await supabase.from('reports').insert({reporter_id:user.id,post_id:id,reason})};
async function loadConversations(){const {data}=await supabase.from('conversation_members').select('conversation_id,conversations(id,created_at)').eq('user_id',user.id);$('conversations').innerHTML=(data||[]).map(x=>`<button onclick="openConversation('${x.conversation_id}')">Conversation</button>`).join('')||'<p>No conversations yet.</p>'}
window.openConversation=async id=>{const {data}=await supabase.from('messages').select('id,content,created_at,sender_id').eq('conversation_id',id).is('removed_at',null).order('created_at');$('messages').innerHTML=(data||[]).map(m=>`<p><b>${m.sender_id===user.id?'You':'User'}:</b> ${escapeHtml(m.content)}</p>`).join('');$('messageForm').hidden=false;$('messageForm').dataset.conversation=id};
$('messageForm').addEventListener('submit',async e=>{e.preventDefault();const conversation_id=e.currentTarget.dataset.conversation;const content=$('message').value.trim();if(!content)return;await supabase.from('messages').insert({conversation_id,sender_id:user.id,content});$('message').value='';openConversation(conversation_id)});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
supabase.auth.onAuthStateChange((_e,session)=>{user=session?.user||null;render();if(user)loadPosts()});init();