import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://pmwagzylqgxzigtizaqb.supabase.co','sb_publishable_27JdPAJXuxnfgBpHQCFDzA__6-uJcMh');
const $=id=>document.getElementById(id);let user=null,profile=null,generalId=null,refreshTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){const {data}=await supabase.auth.getSession();user=data.session?.user||null;if(user)await boot();render()}
async function boot(){const r=await supabase.from('profiles').select('*').eq('id',user.id).single();profile=r.data;if(profile?.is_admin)$('adminTab').hidden=false;await loadPosts();await loadProfile();startLiveRefresh()}
function render(){$('auth').hidden=!!user;$('app').hidden=!user}
function startLiveRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(!user)return;if(!$('feed').hidden)loadPosts();if(!$('chat').hidden&&generalId)renderMessages()},1000)}
$('signup').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabase.auth.signUp({email:$('email').value,password:$('password').value,options:{data:{username:$('username').value.trim(),display_name:$('username').value.trim()}}});if(error)return $('authMsg').textContent=error.message;if(data.user){user=data.user;await boot();render()}};
$('login').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error)return $('authMsg').textContent=error.message;user=data.user;await boot();render()};$('logout').onclick=async()=>{clearInterval(refreshTimer);await supabase.auth.signOut();user=null;render()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{const t=b.dataset.tab;for(const id of ['feed','chat','profile','admin'])$(id).hidden=id!==t;if(t==='feed')loadPosts();if(t==='chat')loadGeneralChat();if(t==='profile')loadProfile();if(t==='admin')loadReports()});
async function loadPosts(){const {data,error}=await supabase.from('posts').select('id,media_url,media_type,caption,created_at,user_id').is('removed_at',null).order('created_at',{ascending:false}).limit(100);if(error)return $('posts').innerHTML='<p>Could not load posts: '+esc(error.message)+'</p>';const ids=[...new Set((data||[]).map(p=>p.user_id))];let names={};if(ids.length){const r=await supabase.from('profiles').select('id,username').in('id',ids);if(r.error)return $('posts').innerHTML='<p>Could not load usernames: '+esc(r.error.message)+'</p>';(r.data||[]).forEach(x=>names[x.id]=x.username)}$('posts').innerHTML=(data||[]).map(p=>`<article class="post"><div class="meta"><b>@${esc(names[p.user_id]||'user')}</b> · ${new Date(p.created_at).toLocaleString()}</div>${p.caption?`<p>${esc(p.caption)}</p>`:''}${p.media_type==='video'?`<video src="${esc(p.media_url)}" controls playsinline></video>`:`<img src="${esc(p.media_url)}" alt="ELF post">`}<button onclick="reportPost('${p.id}')">Report</button>${p.user_id===user.id?`<button onclick="deletePost('${p.id}')">Delete</button>`:''}</article>`).join('')||'<div class="empty">No posts yet. Be the first.</div>'}
function uploadWithProgress(path,file,token,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`https://pmwagzylqgxzigtizaqb.supabase.co/storage/v1/object/elf-media/${path}`);xhr.setRequestHeader('Authorization',`Bearer ${token}`);xhr.setRequestHeader('apikey','sb_publishable_27JdPAJXuxnfgBpHQCFDzA__6-uJcMh');xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100),e.loaded,e.total)};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(xhr.responseText||`Upload failed (${xhr.status})`));xhr.onerror=()=>reject(new Error('Network error while uploading.'));xhr.onabort=()=>reject(new Error('Upload cancelled.'));xhr.send(file)})}
$('postForm').onsubmit=async e=>{e.preventDefault();const file=$('media').files[0];if(!file)return alert('Choose an image or video first.');if(!(file.type.startsWith('image/')||file.type.startsWith('video/')))return alert('Only images and videos are allowed.');if(file.size>100*1024*1024)return alert('Maximum file size is 100 MB.');const box=$('uploadBox'),bar=$('uploadProgress'),txt=$('uploadText'),btn=$('postButton');box.hidden=false;btn.disabled=true;bar.value=0;txt.textContent='Uploading… 0%';try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Your session expired. Please log in again.');const ext=(file.name.split('.').pop()||'bin').toLowerCase(),type=file.type.startsWith('video/')?'video':'image',path=`${user.id}/${crypto.randomUUID()}.${ext}`;await uploadWithProgress(path,file,session.access_token,pct=>{bar.value=pct;txt.textContent=`Uploading… ${pct}%`});txt.textContent='Publishing post…';const {data:{publicUrl}}=supabase.storage.from('elf-media').getPublicUrl(path);const r=await supabase.from('posts').insert({user_id:user.id,media_url:publicUrl,media_type:type,caption:$('caption').value.trim()});if(r.error)throw new Error(r.error.message);bar.value=100;txt.textContent='Upload complete ✓ 100%';$('postForm').reset();await loadPosts();setTimeout(()=>box.hidden=true,1500)}catch(err){txt.textContent='Upload failed';alert(err.message)}finally{btn.disabled=false}};
window.deletePost=async id=>{if(!confirm('Delete this post?'))return;const r=await supabase.from('posts').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',id).eq('user_id',user.id);if(r.error)alert(r.error.message);else loadPosts()};window.reportPost=async id=>{const reason=prompt('Why are you reporting this post?');if(reason?.trim()){const r=await supabase.from('reports').insert({reporter_id:user.id,post_id:id,reason:reason.trim()});if(r.error)alert(r.error.message)}};
async function loadGeneralChat(){let r=await supabase.from('conversations').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle();if(r.error)return $('messages').innerHTML='<p>'+esc(r.error.message)+'</p>';if(!r.data){r=await supabase.from('conversations').insert({}).select('id').single();if(r.error)return $('messages').innerHTML='<p>'+esc(r.error.message)+'</p>'}generalId=r.data.id;$('chatTitle').innerHTML='<b>🌐 General Chat</b>';await renderMessages()}
async function renderMessages(){if(!generalId)return;const {data,error}=await supabase.from('messages').select('id,content,created_at,sender_id').eq('conversation_id',generalId).is('removed_at',null).order('created_at').limit(300);if(error)return $('messages').innerHTML='<p>'+esc(error.message)+'</p>';const ids=[...new Set((data||[]).map(m=>m.sender_id))];let names={};if(ids.length){const r=await supabase.from('profiles').select('id,username').in('id',ids);(r.data||[]).forEach(x=>names[x.id]=x.username)}$('messages').innerHTML=(data||[]).map(m=>`<div class="msg ${m.sender_id===user.id?'mine':''}"><b>@${esc(names[m.sender_id]||'user')}</b><span>${esc(m.content)}</span><small>${new Date(m.created_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div>`).join('')||'<p class="muted">No messages yet. Say hello!</p>';$('messageForm').hidden=false;$('messages').scrollTop=$('messages').scrollHeight}
$('messageForm').onsubmit=async e=>{e.preventDefault();const content=$('message').value.trim();if(!content||!generalId)return;const r=await supabase.from('messages').insert({conversation_id:generalId,sender_id:user.id,content});if(r.error)alert(r.error.message);else{$('message').value='';renderMessages()}};
async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(!data)return;profile=data;$('myUsername').textContent='@'+data.username;$('myBio').textContent=data.bio||'No bio yet.';$('displayName').value=data.display_name||'';$('bio').value=data.bio||''}$('profileForm').onsubmit=async e=>{e.preventDefault();const r=await supabase.from('profiles').update({display_name:$('displayName').value.trim(),bio:$('bio').value.trim()}).eq('id',user.id);if(r.error)alert(r.error.message);else loadProfile()};
async function loadReports(){if(!profile?.is_admin)return;const {data,error}=await supabase.from('reports').select('id,reason,created_at,post_id,message_id,reporter_id').is('resolved_at',null).order('created_at',{ascending:false});if(error)return $('reports').innerHTML='<p>'+esc(error.message)+'</p>';$('reports').innerHTML=(data||[]).map(r=>`<article class="report card"><b>Report</b><p>${esc(r.reason)}</p>${r.post_id?`<button onclick="moderatePost('${r.post_id}','${r.id}')">Remove post & resolve</button>`:''}${r.message_id?`<button onclick="moderateMessage('${r.message_id}','${r.id}')">Remove message & resolve</button>`:''}</article>`).join('')||'<p class="muted">No unresolved reports.</p>'};window.moderatePost=async(p,r)=>{if(!confirm('Remove this post?'))return;await supabase.from('posts').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',p);await supabase.from('reports').update({resolved_at:new Date().toISOString(),resolved_by:user.id}).eq('id',r);await supabase.from('moderation_actions').insert({admin_id:user.id,target_type:'post',target_id:p,action:'remove'});loadReports()};window.moderateMessage=async(m,r)=>{if(!confirm('Remove this message?'))return;await supabase.from('messages').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',m);await supabase.from('reports').update({resolved_at:new Date().toISOString(),resolved_by:user.id}).eq('id',r);await supabase.from('moderation_actions').insert({admin_id:user.id,target_type:'message',target_id:m,action:'remove'});loadReports()};
supabase.channel('elf-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>user&&!$('feed').hidden&&loadPosts()).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>user&&!$('chat').hidden&&renderMessages()).subscribe();supabase.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user)await boot();render()});init();