import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://pmwagzylqgxzigtizaqb.supabase.co','sb_publishable_27JdPAJXuxnfgBpHQCFDzA__6-uJcMh');
const $=id=>document.getElementById(id); let user=null, profile=null, activeChat=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){const {data}=await supabase.auth.getSession();user=data.session?.user||null;if(user)await boot();render();}
async function boot(){let r=await supabase.from('profiles').select('*').eq('id',user.id).single();profile=r.data;if(profile?.is_admin)$('adminTab').hidden=false;await loadPosts();await loadProfile();}
function render(){ $('auth').hidden=!!user;$('app').hidden=!user; }
$('signup').onsubmit=async e=>{e.preventDefault();const username=$('username').value.trim();const {data,error}=await supabase.auth.signUp({email:$('email').value,password:$('password').value,options:{data:{username,display_name:username}}});if(error)return $('authMsg').textContent=error.message;if(data.user){user=data.user;await boot();render();$('authMsg').textContent='';}};
$('login').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error)return $('authMsg').textContent=error.message;user=data.user;await boot();render();};
$('logout').onclick=async()=>{await supabase.auth.signOut();user=null;profile=null;render()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{const t=b.dataset.tab;for(const id of ['feed','chat','profile','admin'])$(id).hidden=id!==t;if(t==='feed')loadPosts();if(t==='chat')loadConversations();if(t==='profile')loadProfile();if(t==='admin')loadReports()});
async function loadPosts(){const {data,error}=await supabase.from('posts').select('id,media_url,media_type,caption,created_at,user_id,profiles(username,display_name)').is('removed_at',null).order('created_at',{ascending:false}).limit(100);if(error)return;$('posts').innerHTML=(data||[]).map(p=>`<article class="post"><div class="meta"><b>@${esc(p.profiles?.username||'user')}</b> · ${new Date(p.created_at).toLocaleString()}</div>${p.caption?`<p>${esc(p.caption)}</p>`:''}${p.media_type==='video'?`<video src="${p.media_url}" controls playsinline></video>`:`<img src="${p.media_url}" alt="ELF post">`}<div class="actions"><button onclick="reportPost('${p.id}')">Report</button>${p.user_id===user?.id?`<button onclick="deletePost('${p.id}')">Delete</button>`:''}</div></article>`).join('')||'<div class="empty">No posts yet. Be the first.</div>';}
$('postForm').onsubmit=async e=>{e.preventDefault();const file=$('media').files[0];if(!file)return;if(!['image/','video/'].some(x=>file.type.startsWith(x)))return alert('Only images and videos are allowed.');if(file.size>100*1024*1024)return alert('Maximum file size is 100 MB.');const ext=(file.name.split('.').pop()||'bin').toLowerCase();const type=file.type.startsWith('video/')?'video':'image';const path=`${user.id}/${crypto.randomUUID()}.${ext}`;let r=await supabase.storage.from('elf-media').upload(path,file,{contentType:file.type,upsert:false});if(r.error)return alert(r.error.message);const {data:{publicUrl}}=supabase.storage.from('elf-media').getPublicUrl(path);r=await supabase.from('posts').insert({user_id:user.id,media_url:publicUrl,media_type:type,caption:$('caption').value.trim()});if(r.error)alert(r.error.message);else{$('postForm').reset();loadPosts();}};
window.deletePost=async id=>{if(!confirm('Delete this post?'))return;const r=await supabase.from('posts').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',id).eq('user_id',user.id);if(r.error)alert(r.error.message);else loadPosts()};
window.reportPost=async id=>{const reason=prompt('Reason for report?');if(reason?.trim()){const r=await supabase.from('reports').insert({reporter_id:user.id,post_id:id,reason:reason.trim()});if(r.error)alert(r.error.message);else alert('Report submitted.')}};
$('userSearch').oninput=async e=>{const q=e.target.value.trim();if(q.length<2)return $('userResults').innerHTML='';const {data}=await supabase.from('profiles').select('id,username,display_name').ilike('username',`%${q}%`).neq('id',user.id).limit(10);$('userResults').innerHTML=(data||[]).map(p=>`<button class="user" onclick="startChat('${p.id}','${esc(p.username)}')">@${esc(p.username)}</button>`).join('')};
window.startChat=async(recipientId,name)=>{const {data,error}=await supabase.rpc('create_elf_conversation',{recipient_id:recipientId});if(error)return alert(error.message);activeChat=data;$('chatTitle').textContent='Chat with @'+name;$('messageForm').hidden=false;await loadConversations();await openConversation(activeChat)};
async function loadConversations(){const {data}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',user.id);const ids=(data||[]).map(x=>x.conversation_id);if(!ids.length)return $('conversations').innerHTML='<p class="muted">No conversations yet.</p>';const {data:members}=await supabase.from('conversation_members').select('conversation_id,user_id,profiles(username)').in('conversation_id',ids);$('conversations').innerHTML=(members||[]).filter(m=>m.user_id!==user.id).map(m=>`<button class="user" onclick="openConversation('${m.conversation_id}')">@${esc(m.profiles?.username||'user')}</button>`).join('')};
window.openConversation=async id=>{activeChat=id;const {data:members}=await supabase.from('conversation_members').select('user_id,profiles(username)').eq('conversation_id',id);const other=(members||[]).find(m=>m.user_id!==user.id);$('chatTitle').textContent=other?'Chat with @'+other.profiles.username:'Conversation';const {data}=await supabase.from('messages').select('id,content,created_at,sender_id').eq('conversation_id',id).is('removed_at',null).order('created_at');$('messages').innerHTML=(data||[]).map(m=>`<div class="msg ${m.sender_id===user.id?'mine':''}"><span>${esc(m.content)}</span><small>${new Date(m.created_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div>`).join('');$('messageForm').hidden=false};
$('messageForm').onsubmit=async e=>{e.preventDefault();const content=$('message').value.trim();if(!content||!activeChat)return;const r=await supabase.from('messages').insert({conversation_id:activeChat,sender_id:user.id,content});if(r.error)alert(r.error.message);else{$('message').value='';openConversation(activeChat)}};
async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(!data)return;profile=data;$('myUsername').textContent='@'+data.username;$('myBio').textContent=data.bio||'No bio yet.';$('displayName').value=data.display_name||'';$('bio').value=data.bio||'';}
$('profileForm').onsubmit=async e=>{e.preventDefault();const r=await supabase.from('profiles').update({display_name:$('displayName').value.trim(),bio:$('bio').value.trim()}).eq('id',user.id);if(r.error)alert(r.error.message);else loadProfile()};
async function loadReports(){if(!profile?.is_admin)return;const {data,error}=await supabase.from('reports').select('id,reason,created_at,post_id,message_id,reporter_id,profiles!reports_reporter_id_fkey(username)').is('resolved_at',null).order('created_at',{ascending:false});if(error)return $('reports').innerHTML='<p>'+esc(error.message)+'</p>';$('reports').innerHTML=(data||[]).map(r=>`<article class="report card"><b>Report</b><p>${esc(r.reason)}</p><div class="meta">@${esc(r.profiles?.username||'user')} · ${new Date(r.created_at).toLocaleString()}</div>${r.post_id?`<button onclick="moderatePost('${r.post_id}','${r.id}')">Remove post & resolve</button>`:''}${r.message_id?`<button onclick="moderateMessage('${r.message_id}','${r.id}')">Remove message & resolve</button>`:''}</article>`).join('')||'<p class="muted">No unresolved reports.</p>';}
window.moderatePost=async(postId,reportId)=>{if(!confirm('Remove this post?'))return;await supabase.from('posts').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',postId);await supabase.from('reports').update({resolved_at:new Date().toISOString(),resolved_by:user.id}).eq('id',reportId);await supabase.from('moderation_actions').insert({admin_id:user.id,target_type:'post',target_id:postId,action:'remove'});loadReports();};
window.moderateMessage=async(messageId,reportId)=>{if(!confirm('Remove this message?'))return;await supabase.from('messages').update({removed_at:new Date().toISOString(),removed_by:user.id}).eq('id',messageId);await supabase.from('reports').update({resolved_at:new Date().toISOString(),resolved_by:user.id}).eq('id',reportId);await supabase.from('moderation_actions').insert({admin_id:user.id,target_type:'message',target_id:messageId,action:'remove'});loadReports();};
supabase.channel('elf-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>{if(user&&!$('feed').hidden)loadPosts()}).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>{if(user&&activeChat&&!$('chat').hidden)openConversation(activeChat)}).subscribe();
supabase.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user)await boot();render()});init();